### ISSUE TITLE
BIOS

### ISSUE THREAD

**Issue by jake99x3** [vinodhmoodley/hackintosh-Z390-A-Pro#1]
Question- What bios version are you running? Have had trouble getting a stable install going using integrated graphics

**Comment by vinodhmoodley** [comment]
I’m using 7B98v1D as mentioned in the code. It’s the newest non- beta bios for the board. I haven’t really messed around with the iGPU because I got good results with my 5700 XT. 

However, since I haven’t  messed with the system in a while, i’ll try building a new EFI from scratch using the iGPU only and see what happens. If I get it working properly, I’ll include the EFI here.

**Comment by jake99x3** [comment]
Appreciate it 🙏
